import { getProviderCredential } from '../../config/provider-vault.mjs';
const mask=(mobile)=>`${mobile.slice(0,2)}******${mobile.slice(-2)}`;
async function postJson(url,body,headers={}){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});if(!r.ok)throw new Error(`Provider HTTP ${r.status}`);return r.json().catch(()=>({}));}
const providers={
 mock:{async send(mobile,code){return {provider:'mock',messageId:`sms_${Date.now()}`,mobileMasked:mask(mobile),accepted:true,debugCode:process.env.NODE_ENV==='production'?undefined:code};}},
 msg91:{async send(mobile,code,mode='test'){const c=getProviderCredential('otp','msg91',mode)||{authKey:process.env.MSG91_AUTH_KEY,templateId:process.env.MSG91_TEMPLATE_ID};if(!c.authKey||!c.templateId)throw new Error('MSG91 credentials not configured');const data=await postJson('https://control.msg91.com/api/v5/otp',{template_id:c.templateId,mobile,otp:code},{authkey:c.authKey});return {provider:'msg91',messageId:data.request_id||data.message||`msg91_${Date.now()}`,mobileMasked:mask(mobile),accepted:true};}},
 twilio:{async send(mobile,code,mode='test'){const c=getProviderCredential('otp','twilio',mode)||{};if(!c.accountSid||!c.authToken||!c.from)throw new Error('Twilio credentials not configured');const auth=Buffer.from(`${c.accountSid}:${c.authToken}`).toString('base64');const body=new URLSearchParams({To:mobile,From:c.from,Body:`Your verification code is ${code}`});const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${c.accountSid}/Messages.json`,{method:'POST',headers:{authorization:`Basic ${auth}`,'content-type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(`Twilio HTTP ${r.status}`);const data=await r.json();return {provider:'twilio',messageId:data.sid,mobileMasked:mask(mobile),accepted:true};}}
};
export const getOtpAdapter=(code)=>{const a=providers[code];if(!a)throw new Error(`Unsupported OTP provider: ${code}`);return a;};
