export const BOOKING_TRANSITIONS = Object.freeze({
  DRAFT: ['SEARCHING', 'CANCELLED_BY_PASSENGER'],
  SEARCHING: ['DRIVER_ASSIGNED', 'NO_DRIVER_FOUND', 'CANCELLED_BY_PASSENGER', 'CANCELLED_BY_ADMIN'],
  DRIVER_ASSIGNED: ['DRIVER_ARRIVING', 'CANCELLED_BY_PASSENGER', 'CANCELLED_BY_DRIVER', 'CANCELLED_BY_ADMIN'],
  DRIVER_ARRIVING: ['DRIVER_ARRIVED', 'CANCELLED_BY_PASSENGER', 'CANCELLED_BY_DRIVER', 'CANCELLED_BY_ADMIN'],
  DRIVER_ARRIVED: ['OTP_VERIFIED', 'NO_SHOW', 'CANCELLED_BY_PASSENGER', 'CANCELLED_BY_DRIVER', 'CANCELLED_BY_ADMIN'],
  OTP_VERIFIED: ['IN_PROGRESS', 'CANCELLED_BY_ADMIN'],
  IN_PROGRESS: ['COMPLETED', 'CANCELLED_BY_ADMIN'],
  COMPLETED: [],
  CANCELLED_BY_PASSENGER: [],
  CANCELLED_BY_DRIVER: [],
  CANCELLED_BY_ADMIN: [],
  NO_DRIVER_FOUND: [],
  NO_SHOW: [],
});

export function assertTransition(from, to) {
  const allowed = BOOKING_TRANSITIONS[from];
  if (!allowed) throw new Error(`Unknown booking status: ${from}`);
  if (!allowed.includes(to)) throw new Error(`Invalid booking transition: ${from} -> ${to}`);
}
