import 'package:flutter/material.dart';
import '../design/astride_theme.dart';

class RideOptionsScreen extends StatefulWidget { const RideOptionsScreen({super.key}); @override State<RideOptionsScreen> createState()=>_RideOptionsScreenState(); }
class _RideOptionsScreenState extends State<RideOptionsScreen>{int selected=0; final rides=[('Toto','2 min','₹25',Icons.electric_rickshaw_rounded),('Auto','4 min','₹40',Icons.local_taxi_rounded),('Bike','3 min','₹35',Icons.two_wheeler_rounded)];
@override Widget build(BuildContext context)=>Scaffold(appBar: AppBar(title: const Text('Choose a ride')),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[
  Expanded(child:ListView.separated(itemCount:rides.length,separatorBuilder:(_,__)=>const SizedBox(height:12),itemBuilder:(context,i){final r=rides[i];final active=i==selected;return InkWell(onTap:()=>setState(()=>selected=i),borderRadius:BorderRadius.circular(20),child:AnimatedContainer(duration:const Duration(milliseconds:180),padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:active?AstrideColors.green:AstrideColors.border,width:active?2:1)),child:Row(children:[Container(width:58,height:58,decoration:BoxDecoration(color:const Color(0x1422C55E),borderRadius:BorderRadius.circular(16)),child:Icon(r.$4,color:AstrideColors.green,size:32)),const SizedBox(width:16),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(r.$1,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700)),Text('${r.$2} away',style:const TextStyle(color:AstrideColors.muted))])),Text(r.$3,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800,color:AstrideColors.navy))])));})) ,
  const SizedBox(height:12),Card(child:ListTile(leading:const Icon(Icons.payments_outlined,color:AstrideColors.green),title:const Text('Cash',style:TextStyle(fontWeight:FontWeight.w600)),trailing:const Icon(Icons.chevron_right_rounded))),const SizedBox(height:12),FilledButton(onPressed:(){},child:const Text('CONFIRM RIDE'))])));
}
